spring:
  application:
    name: ServiceProvider
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/saml?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: xuelei
    password: xuelei
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    show-sql: false
    generate-ddl: true

sp:
  responseUrl: http://10.113.114.188:8080/api/v1

server:
  port: 9001