spring:
  application:
    name: IdentityProvider
  datasource:
    url: jdbc:mysql://192.168.2.10:3306/saml?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: xuelei
    password: xuelei01
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    show-sql: false
    generate-ddl: true

idp:
  entityId: xuelei.mockidp

server:
  port: 8888
